### ISSUE TITLE
Message:     Undefined index: prefix in Job.php

### ISSUE THREAD

**Issue by nletech** [resque/php-resque#31]
i used version is "resque/php-resque": "v1.3.4"

A PHP Error was encountered

Severity:    Notice
Message:     Undefined index: prefix
Filename:    Resque/vendor/resque/php-resque/lib/Resque/Job.php
Line Number: 145

## Expected Behavior

i don't know how to set prefix to my jobs

thanks
## My Environment

* PHP-Resque version: v1.3.4
* PHP version: 7.2
* Redis version: 3.0.7
* Server type and version:
* Operating System and version:

**Comment by danhunsaker** [comment]
The prefix automatically defaults to the empty string. Your queue seems to have jobs on it that weren't queued by PHP-Resque, which is why they're missing that particular field. As of right now, PHP-Resque isn't compatible with other Resque implementations running on the same queues.

**Comment by mrliptontea** [comment]
Hi, I have recently ran into this. In this case, the job was being retried using resque-web UI. I compared the payloads:

* Job scheduled by **php-resque**:
    ```
    object(Resque_Job)#24 (5) {
      ["queue"] => string(37) "my-queue"
      ["worker"] => NULL
      ["payload"] => array(5) {
        ["class"] => string(26) "Acme\Jobs\ProcessFile"
        ["args"] => array(1) {
          [0] => array(1) {
            ["_id"] => string(24) "507f1f77bcf86cd799439011"
          }
        }
        ["id"] => string(32) "65224ac0fcea843d530e1b73e04df6ba"
        ["prefix"] => string(0) ""
        ["queue_time"] => float(1585818561.3695)
      }
      ["instance":"Resque_Job":private] => NULL
      ["jobFactory":"Resque_Job":private] => NULL
    }
    ```

* Job scheduled by [**resque-web**](https://github.com/resque/resque-web):
    ```
    object(Resque_Job)#24 (5) {
      ["queue"] => string(37) "my-queue"
      ["worker"] => NULL
      ["payload"] => array(2) {
        ["class"] => string(26) "Acme\Jobs\ProcessFile"
        ["args"] => array(1) {
          [0] => array(1) {
            ["_id"] => string(24) "507f1f77bcf86cd799439011"
          }
        }
      }
      ["instance":"Resque_Job":private] => NULL
      ["jobFactory":"Resque_Job":private] => NULL
    }
    ```

Looking at the Job it seems that not having an id is allowed since tracking/monitoring is an optional feature:
https://github.com/resque/php-resque/blob/7dd1474f73d5f2a4356cb2f69bd403476606c16e/lib/Resque/Job.php#L128-L132

So the Worker should also respect that and check whether it's possible to update the status:
https://github.com/resque/php-resque/blob/7dd1474f73d5f2a4356cb2f69bd403476606c16e/lib/Resque/Worker.php#L276-L283

I'd like to hear your thoughts on this but I'm happy to open a PR with a fix.

**Comment by danhunsaker** [comment]
Please do!
