### ISSUE TITLE
bin/resque In this file, $worker->logLevel = $logLevel; The logLevel attribute is not supported in the worker class.

### ISSUE THREAD

**Issue by misterpancn** [resque/php-resque#39]
In this file, `$worker->logLevel = $logLevel;` The logLevel attribute is not supported in the worker class.

**Comment by vkatochka** [comment]
The worker was started without the LOGGING, VERBOSE variables. Got a message like "[notice] Starting work on".  A quick search showed that variable "$logLevel" in file "resque/php-resque/bin/resque" has value "false".

**Comment by misterpancn** [comment]
@vkatochka LOGGING, VERBOSE these two configurations only affect the file'resque/php-resque/bin/resque'. The logger in Resque_Worker is not set unless the bin/resque file is modified.

**Comment by danhunsaker** [comment]
This was a case of a change in the way Resque works not being propagated to the bin. Instead of configuring the logger level on the worker, we now directly set the logger instance, which lets Resque support any PSR-compliant logger, such as the one used by $framework.

This has been fixed, now, so I'm closing the issue. Sorry for the long delay on getting to it.
